joint_1_controller:
  type: "effort_controllers/JointPositionController"
  joint: joint_1
  pid: {p: 700.0, i: 50.0, d: 70.0}
joint_2_controller:
  type: "effort_controllers/JointPositionController"
  joint: joint_2
  pid: {p: 700.0, i: 50.0, d: 70.0}
